################################################################################
##########################iDENTIFY RELEVANT FLOATS##############################
################################################################################
#getMetaData takes a list of parameters as input (e.g., "CHL","BBP","DOXY", and identifies profiles
#in argo_bio-profile_index.txt containing these parameters and matching other 
#user-specified criteria (see arguments below). Function saves a list of profiles
#as a CSV file. This file is then used to download Sprof.nc files from the dac in subsequent functions.

###Arguments:###
###params: parameters to be included in profile list; only profiles containing
###all specified parameters will be retained. Default is c("BBP","CHL")
###includedBains: basins to be included in profile list; see basinList.txt for
###available options. Default is NA
###excludedBasins: basins to be excluded in profile list. Default is NA.
###maxElevation: maximum sea floor elevation to be allowed in profile list. If
###timeseries is TRUE, only time series where more than 25 percent of profiles
###have an elevation greater than maxElevation will be retained. Default is NA
###timeseries: If TRUE, profile list will contain list of floats containing at
###least 1 annual timeseries. If FALSE, profile list will contain list of profiles
###matching criteria specified by other arguments. Default is FALSE.
getMetaData(includedBasins = c("Arabian","Atlantic_Eq","Atlantic_N","Atlantic_S",
                               "Bengal","Pacific_Eq","Indian","Black",
                               "Indian_Eq","Med_E","Med_W","Pacific_N",
                               "Polar","Red","Pacific_S","Southern"),
            excludedBasins = "Black",
            timeseries = TRUE)

getMetaData_DOXY(includedBasins = c("Arabian","Atlantic_Eq","Atlantic_N","Atlantic_S",
                               "Bengal","Pacific_Eq","Indian","Black",
                               "Indian_Eq","Med_E","Med_W","Pacific_N",
                               "Polar","Red","Pacific_S","Southern"),
            excludedBasins = "Black",
            timeseries = TRUE)

################################################################################
######################CONVERT _SPROF.NC FILES TO .CSV###########################
################################################################################
#ncImport function takes a list of floats as generated by the getMetadata function,
#downloads the corresponding Sprof.nc files from the dac and generates a .CSV file
#that is saved to a local directory. NOTE: downloading global timeseries data 
#requires ~10 GB.

###Arguments:###################################################################
###floatData: list of profiles to be downloaded from DAC.
###ftpPath: ftp address for dac. Default is "ftp://ftp.ifremer.fr/ifremer/argo/dac/"
###outputDir: local directory where .CSV files should be saved. Default is FALSE.
###Default is "data/rawCSV/"
###overwrite: if TRUE, .CSV files will be saved over any existing files in the outputDir
###all specified parameters will be retained. Default is c("BBP","CHL")
###includedBains: basins to be included in profile list; see basinList.txt for
###available options. Default is NA
###excludedBasins: basins to be excluded in profile list. Default is NA.
###maxElevation: maximum sea floor elevation to be allowed in profile list. If
###timeseries is TRUE, only time series where more than 25 percent of profiles
###have an elevation greater than maxElevation will be retained. Default is NA
###timeseries: If TRUE, profile list will contain list of floats containing at
###least 1 annual timeseries. If FALSE, profile list will contain list of profiles
###matching criteria specified by other arguments. Default is FALSE.
ncImport(overwrite=TRUE)

################################################################################
##################APPLY QC DATA PARAMETER TO MEASUREMENTS#######################
########################REMOVE INCOMPLETE PROFILES##############################
################################################################################

###ARGUMENTS:###################################################################
###inputDirectory: Directory containing .CSV files prepared by ncImport.
###Default is "data/rawCSV/"
###outputDirectory: Directory to use when saving corrected .CSV files.
###Default is "data/qcCSV/"
###overwrite: If TRUE replaces existing files in outputDirectory. If FALSE 
###skips existing files in outputDirectory. Default is FALSE
###unlink: If TRUE deletes files in inputDirectory after saving corresponding
###file in outputDirectory. Default is FALSE.
csvQC(overwrite=TRUE,unlink=FALSE)


################################################################################
######################APPLY dPRES CORRECTIONS + FILTERS#########################
################################################################################

###ARGUMENTS:###################################################################
###inputDirectory: Directory containing .CSV files prepared by ncImport.
###Default is "data/qcCSV/"
###outputDirectory: Directory to use when saving corrected .CSV files.
###Default is "data/finalCSV/"
###overwrite: If TRUE replaces existing files in outputDirectory. If FALSE 
###skips existing files in outputDirectory. Default is FALSE
###unlink: If TRUE deletes files in inputDirectory after saving corresponding
###file in outputDirectory. Default is FALSE.
zoo_prof <- read.csv("data/bbp_zoo_index_all.csv",sep="/", header=F)
rm_zoo(zoo_prof)

csvAdjust(inputDirectory = "data/Chla_BBP_data/qcCSV/",
          outputDirectory = "data//Chla_BBP_data/finalCSV/",
          overwrite=TRUE,unlink=FALSE)

csvAdjust_DOXY(inputDirectory = "data/qcCSV/",
          outputDirectory = "data/finalCSV/",
          overwrite=TRUE,unlink=FALSE)

clean(outputDirectory="data/Chla_BBP_data/finalCSV/", audit=read.table("new_audit.txt", header = TRUE, sep=","))

#########################
mld(fileList=list.files("data/Chla_BBP_data/finalCSV/",pattern=".csv",full.names = F),plot=F)
#########################

fileList<-list.files("data/Chla_BBP_data/finalCSV/",
                     full.names = F,pattern=".csv")
province(fileList, inputDirectory = "data/Chla_BBP_data/finalCSV/",
         outputDirectory = "data/Chla_BBP_data/finalCSV/") #charge zone and par_prof functions

parEstimator(inputDirectory = "data/Chla_BBP_data/finalCSV/", outputDirectory = "data/Chla_BBP_data/parData/", plot=F)

#########################

fileList<-list.files("data/Chla_BBP_data/finalCSV/",
                     full.names = F,pattern=".csv")
parFiles<-list.files("data/Chla_BBP_data/parData",pattern=".csv",
                     full.names = T)
isolumes(fileList,parFiles)



